### ISSUE TITLE
NameError: name 'host' is not defined when using Photon library

### ISSUE THREAD

**Issue by bhavsec** [s0md3v/Photon#109]
Code: 

```
import photon
result = photon.crawl('http://google.com')
print(result)
```

Output:

```
Traceback (most recent call last):
  File "c:/Users/BhavKaran/Documents/reconspider/plugins/emailosint.py", line 2, in <module>
    result = photon.crawl('http://google.com')
  File "C:\Users\BhavKaran\AppData\Local\Programs\Python\Python37\lib\site-packages\photon\photon.py", line 269, in crawl
    domain_name = topLevel(main_url) # Extracts domain out of the url
  File "C:\Users\BhavKaran\AppData\Local\Programs\Python\Python37\lib\site-packages\photon\photon.py", line 250, in topLevel
    ext = tld.get_tld(host, fix_protocol=True)
NameError: name 'host' is not defined
```

**Comment by tomgoody** [comment]
Were you ever able to resolve this issue?  I'm running into the same thing.

**Comment by s0md3v** [comment]
The issue has been fixed :)
Use the following command to upgrade
`pip install photon --upgrade`

**Comment by irshadshalu** [comment]
@s0md3v this is still not resolved as the downloadable version on https://pypi.org/project/photon/1.1.9/#description still contains 1.1.8.2 artifacts.
